language: go
go:
  - "1.11"

git:
  depth: 10

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - go get -u -v github.com/gohugoio/hugo

script:
  - hugo

before_deploy:
  - hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: public
    target_branch: master
    on:
      branch: hugo-site
