name: github pages

on:
  push:
    branches:
      - hugo-site

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.53'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy to GH Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
            target_branch: master
            build_dir: public
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}